### ISSUE TITLE
Is Azure OpenAI supported?

### ISSUE THREAD

**Issue by d5ve** [cloving-ai/cloving-cli#71]
Hi,

Cloving looks great thanks.

Does it support Azure's hosted OpenAI endpoints?

https://learn.microsoft.com/en-us/azure/ai-services/openai/overview

As far as I'm aware, they "talk" the same as OpenAI, but use a different endpoint host/path.

I can see that `~/.clovingconfig` doesn't have endpoint data, and that the adapters each have hardcoded endpoints, but I don't know much about typescript.

Cheers,

Dave

**Comment by cardmagic** [comment]
Thank you Dave for the suggestion, the Azure OpenAI endpoint has been added in 0.3.10. 

You can update via: `npm install -g cloving@latest`

**Comment by RWKotulski** [comment]
That's awesome! Thanks!

**Comment by d5ve** [comment]
Wonderful @cardmagic! I'll test this out today.
